### ISSUE TITLE
is there a recipe for a redis cluster?

### ISSUE THREAD

**Issue by zcaudate** [re-ops/re-cipes#1]
I'm still trying to figure how re-ops works and how to write recipes.

I want to start off with provisioning a couple of redis instances forming a cluster on a bare metal machine over ssh (not using containers).

Is there a basic example that I can follow along?

**Comment by narkisr** [comment]
Hi @zcaudate there is no recipe for setting up a Redis cluster at the moment, however I wanted to clarify some of the uses case around Re-cipes and Re-ops in general.

The following screencast provide a good overview to what Re-cipes offers https://www.youtube.com/watch?v=CBLJiXHbHEI

I also recommend checking out https://re-ops.github.io/re-docs/quickstart/

Feel free to ask any follow up question you might have

**Comment by zcaudate** [comment]
@narkisr thanks for the detailed explanation. I didn't quite understand why there were so many `re-` packages but I see how they fit together.

I have a couple for questions:

1. what is the benefit of having a re-gent executing code as opposed to just connecting over ssh and sending commands remotely?

2. can re-core use an alternate backend to elastic search?

3. with the re-cog serialised functions, how are you managing dependent functions?

4. are you based in Melbourne?

**Comment by narkisr** [comment]
Hi @zcaudate ill will DM you
